steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/ci-payments/payments:$BUILD_ID', '.']
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/ci-payments/payments:$BUILD_ID'
options:
  logging: CLOUD_LOGGING_ONLY
